{% set name = "econci" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38c0c275c94f2e6231c8964ac9225dffe231a94ee7d3ceef34db1c4afa4060de

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - networkx >=2.4
    - numpy >=1.18.1
    - pandas >=0.25.0
    - python

test:
  imports:
    - econci

about:
  home: https://github.com/phcsoares/econci
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Calculates Economic Complexity Indexes
  doc_url: https://github.com/phcsoares/econci
  dev_url: https://github.com/phcsoares/econci

extra:
  recipe-maintainers:
    - phcsoares
